# Generated by Django 2.2.12 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
